input_data:
  file1: "../data/raw/df_final_demo.txt"
  file2: "../data/raw/df_final_experiment_clients.txt"
  file3: "../data/raw/df_final_web_data_pt_1.txt"
  file4: "../data/raw/df_final_web_data_pt_2.txt"

output_data:
  file1: "../data/clean/cleaned_data_1.csv"
  file2: "../data/clean/cleaned_data_2.csv"
  file3: "../data/clean/cleaned_data_3.csv"
  file4: "../data/clean/cleaned_data_3.csv"
  fig1: "../figures/figure1.jpeg"
  fig2: "../figures/figure2.jpeg"
  fig3: "../figures/figure3.jpeg"
  fig4: "../figures/figure4.jpeg"
  fig5: "../figures/figure5.jpeg"
  fig6: "../figures/figure6.jpeg"
  fig7: "../figures/figure7.jpeg"
