input_data:
  file1: "../data/raw/df_final_demo.txt"
  file2: "../data/raw/df_final_experiment_clients.txt"
  file3: "../data/raw/df_final_web_data_pt_1.txt"
  file4: "../data/raw/df_final_web_data_pt_2.txt"

output_data:
  file1: "../data/clean/clean_df_demo.csv"
  file2: "../data/clean/clean_df_demo_variation.csv"
  file3: "../data/clean/clean_df_demo_test.csv"
  file4: "../data/clean/clean_df_demo_control.csv"
  file5: "../data/clean/clean_df_web_data.csv"
  file6: "../data/clean/web_data_control.csv"
  file7: "../data/clean/web_data_test.csv"
  file8: "../data/clean/proc_control_clean.csv"
  file9: "../data/clean/proc_test_clean.csv"
  file10: "../data/clean/proc_control_anomalies.csv"
  file11: "../data/clean/proc_test_anomalies.csv"
  file12: "../data/clean/proc_control_no_out.csv"
  file14: "../data/clean/proc_test_no_out.csv"
  file15: "../data/clean/tableau_web_data.csv"
  fig1: "../figures/figure1.jpeg"
  fig2: "../figures/figure2.jpeg"
  fig3: "../figures/figure3.jpeg"
  fig4: "../figures/figure4.jpeg"
  fig5: "../figures/figure5.jpeg"
  fig6: "../figures/figure6.jpeg"
  fig7: "../figures/figure7.jpeg"
